version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5437
      - DB_NAME=sefareshgiri
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    command: npm run dev

  postgres:
    image: postgres:15-alpine
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=sefareshgiri
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 